### PR TITLE
add header option to set header in "vdropzone-sending" event

### PR DESCRIPTION
**Pull request by moeen-basra**
by updating we can add headers in request

### CODE REVIEW

**Comment by moeen-basra** [comment]
I just submitted a pull request after merging this we can pass the headers object as prop.

`<dropzone id="fileDropZone" url="api/track/upload" v-bind:files="files" />`

`
computed: {
  files() {
    return {
       Authorization: 'bearer: '+ token
    }
  }
}
`

**Comment by rowanwins** [comment]
Hi @moeen-basra 

Thanks for your interest and submitting these pull requests. 
1. I have no problem with the headers property, that all looks fine
2. The idea of programatically adding files onload is a good one but I'm not in favour of adding a watch on the files array. I'd rather see you expose a method on vue-dropzone that you explicitly call. I'd suggest something like 
````
vm.$refs.myDropzone.manuallyAddFile(fileObject)

// and then something like
methods: {
   manuallyAddFile: function (file) {
      this.dropzone.emit('addedfile', file);
      this.dropzone.emit("complete", file);
  }
}
````
The general advice for Vue is to use `watch` pretty sparsely, if possible it's better to be explicit about what is happening especially when dealing with parent-child communications between components.

Let me know if you have any further questions. Thanks again!

**Comment by mirzap** [comment]
Can you add headers property until he works out the second thing. I wouldn't like to use my fork just for that :)

**Comment by moeen-basra** [comment]
I've already added the header property in this fork you can clone this.

**Comment by rowanwins** [comment]
Closing to due to the ability to set headers now being implemented

**Pull request closed without merging**
