### PR TITLE
Allow Dropzone deal with uploads to S3

### PR DESCRIPTION
**Pull request by avikam-pagaya**
This fixes the fact that the file is uploaded twice: once to the S3 endpoint provided, and once to the URL specified in the options.
This error was mentioned here: https://github.com/rowanwins/vue-dropzone/issues/278

### CODE REVIEW

**Comment by vrajroham** [comment]
@avikam-pagaya I appreciate your contribution. You are are exactly right, file is sent twice but it has some reason. While creating this AWS feature, I intentionally sent the file to server with `s3objectlocation` as user may need it for any purpose like, thumbnail creation or it could be anything (better to add feature without removing intended behavior).

As I can see, I'm not seeing that this PR is providing the backward compatibility as we are directly removing image from post data. What i suggest add one more `key` to `awss3` object. Let's say `send_file_to_server = true (default)` and build a logic around that, so backward compatibility will be achieved.

Thanks

**Comment by avikam-pagaya** [comment]
No problem, I didn't realize it was intended behaviour. 
I'd gladly add this possibility.

BTW, did you consider having the transformation needed directly on the s3 object rather than the posted data?

**Comment by ozdemir08** [comment]
I am also having trouble with the same issue. I am trying to upload a file to S3 and save its url to my database. It works for small sized files but when I try to upload a file about 100 mb, then I get validation error which is due to this problem. 

I am waiting for merge.

**Comment by vrajroham** [comment]
@avikam-pagaya @ozdemir08 Your points seems valid. There will very less user base using both the files. I'll create some work around for same and merge this PR.

Thanks

**Comment by avikam-pagaya** [comment]
Hope I didn't step on your toes with this PR, please check out if it's working as you expected.

**Comment by dariaedicas** [comment]
any chances this PR will be merged soon?

**Comment by vrajroham** [comment]
@avikam-pagaya Thanks for your valuable contribution and I apologise to keep waiting to merge this PR. @dariaedicas Updated component has been published to npm with tag  https://github.com/rowanwins/vue-dropzone/releases/tag/v3.1.0

Thanks

**Pull request merged**
