### PR TITLE
Add slot option to form element

### PR DESCRIPTION
**Pull request by keevitaja**
Makes is easy to add hidden fields

### CODE REVIEW

**Comment by rowanwins** [comment]
Gday @keevitaja 

Thanks for this idea, could you possibly contribute some documentation so that people know how to use this feature?

**Comment by keevitaja** [comment]
Hi!

I am not sure if it deserves a dedicated section in the docs, but perhaps this would work:

```
    <dropzone id="myVueDropzone" url="https://httpbin.org/post" v-on:vdropzone-success="showSuccess">
        <!-- Optional parameters if any! -->
        <input type="hidden" name="token" value="xxx">
    </dropzone>
```

**Comment by vrajroham** [comment]
Hey @keevitaja ,

 It's really useful feature when we are using multiple dropzone components on same page / Vue, Also wants to pass tokens and other stuff.

Let's add docs in README.

**Comment by vrajroham** [comment]
Thanks @keevitaja . 👍

**Pull request merged**
