### PR TITLE
Add headers to the sign request.

### PR DESCRIPTION
**Pull request by eggnaube**
Add the ability to add HTTP headers to the sign request (e.g. Bearer Token).

### CODE REVIEW

**Comment by vrajroham** [comment]
I'm testing this PR to merge. Could you provide an example how do I add `"Access-Control-Allow-Origin":"http://aws-direct-s3.dev/"`. I added this to component and now my request does not get initiated. 
Console error pops up `Network Error : Could not send request to AWS. (Maybe CORS error)`. Even I can't debug the request. Please provide some example to reproduce this feature PR.

**Comment by maxalmonte14** [comment]
We need this, otherwise, it is impossible to upload files directly to S3 using Laravel!

**Comment by vrajroham** [comment]
@maxalmonte14 I'll update the docs and release new version.

**Comment by eggnaube** [comment]
@vrajroham @maxalmonte14 Define Request Headers:

```javascript
computed: {
  dropzoneOptions() {
    return {
      ...
      headers: {
        'Access-Control-Allow-Origin': '*',
      },
    };
  },
  awss3() {
    return {
      ...
      headers: {
        'Authorization': 'Bearer <token>',
      },
    };
  },
},
```

**Pull request merged**
