### PR TITLE
Docs corrected

### PR DESCRIPTION
**Pull request by shraiysh**
Issue #386 corrected in Docs [here](https://github.com/rowanwins/vue-dropzone/blob/master/docs/src/pages/Events.vue#L36)

### CODE REVIEW

**Comment by rowanwins** [comment]
Looks good so far @shraiysh - although committing that single file won't actually update the site, so if you'd aso like to update the live site you'll need to run `npm run build-docs`

**Comment by shraiysh** [comment]
Thanks, @rowanwins Built the docs. Please let me know if there's an issue.

**Comment by rowanwins** [comment]
Awesome - the updated docs are live, thanks @shraiysh !

**Comment by shraiysh** [comment]
Thanks for your guidance @rowanwins. This is the first time I have contributed in an open source project and I feel really good about it.

**Pull request merged**
