### PR TITLE
Add slot support for more custom templates

### PR DESCRIPTION
**Pull request by Fohlen**

### CODE REVIEW

**Comment by rowanwins** [comment]
Hi @Fohlen 

Thanks for this pull request and for writing up some associated documentation. We'll do a proper review and try and get it incorporated. We're currently working on a new major release for this component so this would be a good new feature!

**Comment by rowanwins** [comment]
Hi @Fohlen 

I've had a bit of a play at trying to get this working in the `version3` branch but I haven't had any success. I trust that you'd got it working? I'm not very familiar with slots myself, would you mind taking a look at seeing if you could add this functionality to the `version3` branch?

**Comment by Fohlen** [comment]
Hey @rowanwins I will try to have a look t the `v3` branch as soon as I have some free time

**Comment by vrajroham** [comment]
@Fohlen It will be awesome! Thanks

**Comment by vrajroham** [comment]
We have released major version of library and this PR is intended for previous version.
Closing this PR

**Pull request closed without merging**
