### PR TITLE
Adds v-model support to dropzone files

### LINKED ISSUE #441: Files are not reactive
I want to write my own custom dropzone and therefore i need to know the current number of files which are queued. I wrote the following computed property as mentioned in #83:

```
[...]
computed: {
    fileCount() {
      return this.$refs.mydz.dropzone.files.length
    },
  },
[...]
```
Initially the property is set to 0 but when i add files, the computed prop is not updated although files becomes an array with one element.

I tried using method like `getQueuedFiles()` but that did not work as well. 
I obviously could listen to events and manually update the count which seems quite cumbersome.

Has someone an idea how to get the number of files in a reactive fashion?

### PR DESCRIPTION
**Pull request by MatheusRich**
Fixes #441.

I've added a basic support to a v-model directive. So, given a object, we should be able to bind the files in dropzone like this:

```javascript
files: {
  acceptedFiles: [...],
  rejectedFiles: [...],
  queuedFiles: [...],
  uploadingFiles: [...]
}
```

I've called updateFiles() after ALL dropzone events. I'm not sure about this, what do you think? Is there a better way to approach this? Tell me if there's something else to do (or if it has any bugs).

### CODE REVIEW

**Review by edismooth — APPROVED** [review]

**Comment by MatheusRich** [comment]
Fixed the conflicts! I hope the stylesheet is correct. Is there any linter setted up?

**Comment by JohannesLichtenberger** [comment]
Any news on this?

**Comment by MatheusRich** [comment]
@JohannesLichtenberger It seems that this is not being maintained anymore. Check #473

**Comment by JohannesLichtenberger** [comment]
However, how to use https://github.com/Etheryte/vue-auto-dropzone with Nuxt.js? It doesn't support SSR as of now: `window is not defined`.

**Pull request closed without merging**
