### PR TITLE
Don't render component on the server

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by rowanwins** [comment]
Thanks for this fix @ndarilek . I've not really done anything with server-side rendering so this is appreciated!

**Comment by ndarilek** [comment]
No problem! Any word on when it will be published?

**Comment by rowanwins** [comment]
Hi @ndarilek I'll try and get it done tonight.

**Comment by rowanwins** [comment]
HI @ndarilek 

This should now be available via npm as v2.2.0

Cheers

**Comment by ndarilek** [comment]
Thanks!

**Comment by ndarilek** [comment]
You've partially reverted my PR and have undone my fix.

```
<script>
   var Dropzone = require('dropzone')

   export default {
```

My PR specifically *did not* do this because it is not universal. 
Dropzone cannot be required on the server as it attempts to use `window` 
which is not present. With those lines in place, this issue still 
persists, and that's what's present in your released version.

**Comment by ndarilek** [comment]
The only place where you touch `dropzone` as `required` is in `mounted`. 
It isn't enough to simply return if you're on the server. You have to 
move all of the initialization code for Dropzone into this function 
because Dropzone does something after being required that expects 
`window` to be available, which it isn't on the server. The rest should 
be handled by callbacks/Vue methods which aren't run in the context of 
SSR, so are unaffected.

I've been using my PR in an app, and it seemed to work just fine, both 
rendering what was possible on the server while working fully on the 
client. Please merge the PR as submitted, or let me know what in it was 
unworkable while still preserving the fact that dropzone has to be 
required specifically after the SSR guard ensures that it isn't running 
on the server. Thanks for your time and attention.

**Comment by rowanwins** [comment]
Hey @ndarilek 

Im sorry for butchering your pull request, not quite sure what I was thinking. As mentioned previously I don't have any experience with SSR. I'm very intrigued how this module works in SSR if you're not requiring dropzone, that's an investigation for another day :) 

I've republished to npm as version 2.2.1

Cheers
Rowan

**Comment by ndarilek** [comment]
The idea is that it *doesn't* work in SSR, but I'm using it in a 
codebase that mostly does, so I need it to silently do nothing while 
everything around it runs. So if I have 9 other modules, and they all 
work in SSR, the presence of this one module breaks everything on the 
server and introduces rendering errors even if the other 9 modules work 
fine.

Thanks, I'll give the new version a shot.

**Pull request merged**
