### PR TITLE
Add options previewTemplate - callback

### PR DESCRIPTION
**Pull request by LetItFlyPl**

### CODE REVIEW

**Comment by rowanwins** [comment]
Hi @LetItFlyPl 

I currently don't have access to a computer so won't have the ability to accept this request for another week or so sorry. But I will get to it :)

**Comment by vrajroham** [comment]
No worry @rowanwins I'll check the PR! :tada:

**Comment by vrajroham** [comment]
@LetItFlyPl What functionality does **process** button adds? Nothing is related any functionality!

**Comment by rowanwins** [comment]
Hi @vrajroham 

Some of the code, particularly in the App.js file may have been [committed by me here](https://github.com/rowanwins/vue-dropzone/commit/e830fefa5a6274ab6cf9c3636a017127a8463b17). I had to hand my laptop back into my old work upon finishing up so I just committed everything I had. I'm yet to buy myself a new computer for use at home.

**Comment by vrajroham** [comment]
Thanks @rowanwins for pointing it. @LetItFlyPl I think your code make sense, previously I tested your branch. My bad! :frowning_face:

**Comment by LetItFlyPl** [comment]
Ok, @vrajroham can you accept my push request or I have to wait for  @rowanwins to come back?

**Comment by vrajroham** [comment]
@LetItFlyPl Busy with other project right now! Also from log time I have not in sync with project, at night I'll work on it.

**Comment by vrajroham** [comment]
This PR fixes demo application which was not uploading images it's own. (`autoProcessQueue`) Thanks @LetItFlyPl appreciate your contribution, Thanks!

I think @rowanwins you were working on `process` button which will upload files on click ( @rowanwins correct me if I am wrong ), but you had to leave in between due to some reasons. For time being I am merging this change so demo application will be fixed. 

@rowanwins I'll wait for your confirmation for `process` button so I'll contribute behalf you! :smile:

**Pull request merged**
