### PR TITLE
AWS S3 direct upload is ready

### PR DESCRIPTION
**Pull request by vrajroham**
#### Changelog
- [x] Finally AWS Direct S3 upload is done.
- [x] Throulgy test is tobe done
- [x] Documentation to be done (Server side too)
- [ ] Maybe tutorial will be required for this functionality, because server side code too involves. (I'll try to create on [Medium](https://medium.com/)

### CODE REVIEW

**Comment by AlexanderYW** [comment]
With all these demo pages shouldn't we reorganize the demo vue files under a demo directory?

Also do you guys want me to restructure the sidebar so we have a demo section instead of a long list of demo's under the documentation section?

**Comment by rowanwins** [comment]
Gday @AlexanderYW 

The demo pages could be reorganised in directories, I was just cutting and pasting late into the night one night so Im sure they could be improved. Im sure there could be a smarter way to generate them as well either through props or slots.

**Comment by AlexanderYW** [comment]
Awesome, when you are done with this PR. I'm thinking about looking into adding Azure Blob storage as a service too. not sure it will be done for 3.0.0 but maybe 3.1.0

**Comment by vrajroham** [comment]
@AlexanderYW Waw! Really sounds great! If you are familiar with AWS then I would like you to review this feature, even though I'll create complete docs and tutorial for this.

---
@rowanwins @AlexanderYW 
Reason behind this feature/ PR is, I was thinking we should release any additional feature which users will like, as we are shipping with revamped package (That's why I said @rowanwins to hold on
 😄  ). I used this package in my official projects and the additional thing I use with this was S3 upload but it was done from serverside which was redundant as dropzone sends to server and server sends to s3. 

So, I thought why not to build this directly on component with minimum configuration. Really this was the challenging and complex work for me! But I dragged configuration to 10% for this stuff. Hope users will like it. 

Finally I'm done with implementation and testing, may be in a day to two I'll update docs and tutorial.

@AlexanderYW @rowanwins Let me know if you can review/refactor/test PR.

**Comment by AlexanderYW** [comment]
Sadly I am not familiar with AWS :), but by reading code, I think when `addedfile` function is called we upload the file no matter if it's added through `manuallyAddFile` or filepicker/filedrop is that correct?, because then we have a different behavior than when its not AWS :)

Looking forward for when you are finish with it :)

**Comment by vrajroham** [comment]
No `addedfile` is called when file is added to Dropbox. Then if `autoProcessQueue` is true it directly triggers upload else files are added to queue. So queued file we have to process using `processQueue` or `processFile(file)` to upload one by one.

**Comment by lunchboxsuhi** [comment]
Just wondering, is there any milestones to support Azure blob storage?

**Comment by AlexanderYW** [comment]
Hi @lunchboxsuhi, I did look into that, but found it redundant since it can be done by the full azure blob URL with the default upload function from the vue-dropzone

If you have some thoughts on this with a scenario that may require that, please let me know :)

**Comment by lunchboxsuhi** [comment]
@AlexanderYW Is there a way to change the upload URL dynamically based on a callback or promise? currently I need to get all the SAS tokens for azure blob in the `accept` function since it has a `done` parameter and call that once I get all the tokens from my server. However, if I want a fresh token that expires quickly this will become a problem when uploading bigger files during processing. (they might expire).

Currently all the events get fired after one another without a callback or promise, I was wondering if perhaps I missed something in the documentation which can pause the event and I can retrieve the token during the processing event.

And lastly due to having a global URL state I am unable to upload more than 1 file at a time because if I set the URL with 2 files processing they will try to overwrite the same location (SAS url). Would it be possible change the URL for the specific file processing during parallel upload?

if the above is not possible, perhaps adding an option `setUrlOnFileProcess` which contains a callback that will wait for it to be called before continuing might solve this.

**Pull request merged**
