### PR TITLE
Added 'method' as prop. Added String as a valid format to 'clickable'…

### PR DESCRIPTION
**Pull request by gholme4**
… prop.

### CODE REVIEW

**Comment by vrajroham** [comment]
@gholme4 It will be good if you update the docs about your contribution in [README.md](https://github.com/gholme4/vue-dropzone/blob/vue2/README.md)

Thanks. :smiley:

**Comment by vrajroham** [comment]
@gholme4  Commit to same PR

**Comment by gholme4** [comment]
Hi @vrajroham. I updated the docs with my changes. Thanks.

**Comment by rowanwins** [comment]
Thanks for this addition @gholme4 , will push it up to npm when I get a chance

**Pull request merged**
