### PR TITLE
Added slot support

### PR DESCRIPTION
**Pull request by alexbikazzan**
Should solve #308

### CODE REVIEW

**Comment by rowanwins** [comment]
Hi @alexbikazzan

Thanks for this. Any chance you can include an example in the docs as to how and why to use this?

Thanks
Rowan

**Comment by alexbikazzan** [comment]
Absolutely.

The slot allows the developer to insert any html into the dropzone. It is basically extends the "Adding Icon" functionality.

I'll add a new section to the docs and you can decide if you want to keep both sections (since they overlap a bit).

**Comment by SayakMukhopadhyay** [comment]
Addition of slots would be great for customizability.

**Comment by vrajroham** [comment]
@alexbikazzan Thanks for your contribution. This feature is really the handful.


@rowanwins I tried adding input controls but they look very odd on preview pane. Hidden fields will work great in this case. I tried adding hidden fields and submit the form but that fields are not submitting with form. I'll try to extend this PR to include hidden fields while submitting the form.

**Pull request merged**
