### PR TITLE
Fix for add manual file method

### PR DESCRIPTION
**Pull request by vrajroham**
### Fixes

- This fix subtracts manually added file from maxFiles option. Which was allowing the user to add more files than maximum allowed files in the dropbox. (Addition to newly added method `manuallyAddFile()`)

-  Removed redundant documentation from README. (TYPO)

### CODE REVIEW

**Comment by vrajroham** [comment]
@rowanwins I think we should `REMOVE` button from files which are added manually. Because even if we remove that file from dropbox it's not deleted from server.

Even it creates mess with `maxFiles` now because we are reducing `maxFiles` count by 1.
 So, anyway we have to remove `REMOVE` button from manually added file.

Wait for my other commit. I'll work on it.

**Comment by vrajroham** [comment]
Working as expected. Needs more test cases. 😄

**Comment by rowanwins** [comment]
Hey @vrajroham 

Thanks so much for picking that up and the good suggestion for the remove button. 

I've added you as a collaborator on the repo so feel free to make any other contributions directly, I only get to maintain this repo very sporadically!

Cheers

**Comment by vrajroham** [comment]
Thanks @rowanwins I'll try my best!

**Comment by vesper8** [comment]
@rowanwins @vrajroham uhhh dudes.. what? what am I reading here? This project isn't exclusively used in implementations that use Dropbox!! I just opened an issue that you caused by deciding to remove the remove button for manually added files https://github.com/rowanwins/vue-dropzone/issues/94

I am doing my own handling of the remove functionality with an API that's got nothing to do with Dropbox.. and now my remove button has gone missing without explanation.

So the question is, how do I undo your "fix" here? If a user wants to have the remove button showing.. let them! They know what they need... this just broke the 'remove image' functionality I had on a project in production with hundreds of users =/

**Comment by rowanwins** [comment]
Gday @vesper8 

Sorry for the unintentional side-effects, the easiest solution to roll back to a previous version of the plugin via npm, you should be able to do `npm install vue-dropzone2@2.2.6`

Please remember that this project is maintained unfunded, at 10pm at night after a long day at work and looking after kids, occasionally things go astray. If you can work out a better way to handle these edge cases you're welcome to contribute pull requests.

We'll work to try and release a fix

**Comment by vesper8** [comment]
@rowanwins Yes I do understand the nature of open source and if I haven't mentioned it before, though I think I might have because I very often do, I am VERY grateful for this package, and the other 200+ github packages that I use in my projects. I do try and contribute here and there, I guess my bigger contribution is bug reporting

I have reverted back to the commit just before the one that removed the Remove button
```
"vue2-dropzone": "git://github.com/rowanwins/vue-dropzone.git#9b9ceb5",
```

I am just a little frustrated at the decision in this case because.. unless I am missing something.. and maybe I am.. removing the remove button in ALL cases for manually added files just essentially removed the ability to delete files via Dropzone in .. all cases? for all filesystems? How is one expected to be able to remove a file that was previously added (ie not in the current session) with the button completely removed?

I've never used Dropbox to store files.. I don't suppose it's a very wise things to use for files originating from a public-facing website but that's my opinion. But I also don't understand the logic for removing the button "for Dropbox". Surely even Dropbox allows deletion of files.. maybe not automatically but through an api call and a little custom code.

Anyway, sorry if I sounded a little brash.. I do appreciate your work and this library quite a bit.

Cheers

**Pull request merged**
