### PR TITLE
Added different processing events and errormultiple event 

### PR DESCRIPTION
**Pull request by AlexanderYW**
Took the time to add @vrajroham's drag code too same goes for documentation for the events

Beside that until we add a markdown parser for "simple-table" i think we should use `v-html` on the table coulmn so we can style the descriptions of the events

Let me know if you disagree with any of the things i did! :)

### CODE REVIEW

**Comment by vrajroham** [comment]
Awesome work @AlexanderYW . I was planning to take it now!

Cheers 🎉

**Comment by AlexanderYW** [comment]
Thanks!, and that sounds awesome :)!

**Comment by vrajroham** [comment]
Hey @AlexanderYW,
Try [this example](http://vrajroham.me/vue-dropzone-page/#/examples) of dropzone. Look at the events getting fired in table. That was the thought of @rowanwins which I did before and going to incorporate in V3 demo. 

Your suggestions/improvements are welcome.

**Comment by AlexanderYW** [comment]
Awesome would be great for the demo page, the stuff I fixed was with focus of the doc for events :)

But I think more than one demo/example would be awesome like where you can see  the different events in different scenarios :)

**Pull request merged**
