### PR TITLE
add additional parameters to signing request

### PR DESCRIPTION
**Pull request by gborcherds**
I created this pull request. I updated the docs to talk about the three parameters for the signing request that need to be done and I added formData to the signing request. These gives someone full control over the signing request, which is my case is needed and may be needed by others.

Let me know if you want me to change anything.

### CODE REVIEW

**Comment by mv-vrajroham** [comment]
@gborcherds Thanks allot for your contribution. I'll review your request and functionality asap and try to release updated version today itself. So that you can use your features soon.

**Comment by vrajroham** [comment]
@gborcherds Awesome work and indeed feature for signing url request.

**Comment by vrajroham** [comment]
@gborcherds I have released latest version of component with this PR. Now you can enjoy your feature in [3.0.3](https://github.com/rowanwins/vue-dropzone/releases/tag/v3.0.3)

**Comment by gborcherds** [comment]
Thanks, I appreciate the addition.

**Pull request merged**
