### PR TITLE
Added supporting methods, new event

### PR DESCRIPTION
**Pull request by vrajroham**
Added new methods which will expose core functionalities of dropzone.

#### New Methods

| Method | Description |
|------------|-------------|
| getAcceptedFiles() | all accepted files |
| getRejectedFiles() | all rejected files |
| getQueuedFiles() | all queued files |
|getUploadingFiles() | all uploading files |

#### New Events

| Event | Parameters | Description |
|------------|-----------|-------------|
| vdropzone-total-upload-progress | totaluploadprogress `(0 - 100)`, totalBytes, totalBytesSent  | This event can be used to show the overall upload progress of all files. |

### CODE REVIEW

**Comment by vrajroham** [comment]
fixes #48

**Comment by rowanwins** [comment]
Hey @vrajroham thanks so much for your contribution, I'll get a chance over the weekend to review and hopefully accept your commit :)

**Comment by vrajroham** [comment]
Added MIT Licence.

**Comment by rowanwins** [comment]
Thanks so much @vrajroham , I'll tidy up a few other merges and release a new version to npm

**Pull request merged**
