### PR TITLE
Exposing alot of dropzone's methods and added a few more events

### PR DESCRIPTION
**Pull request by AlexanderYW**
Added dropzone methods - Added some of them to the documentation

Added more events - Added some of them to the documentation

The reason i haven't added all of it to the documentation is that dropzone neither do. so either they have a good reason not to or they haven't updated it. What are you guys thoughts should we add all the advance methods and events to the documentation?

### CODE REVIEW

**Comment by vrajroham** [comment]
I think we should expose all the underlying methods, events, options etc. We should provide complete power to end users. Chances of problem would be there, if there's any issue underlying functions then it won't get addressed. Better to provide complete functionality.

**Comment by vrajroham** [comment]
@AlexanderYW I didn't reviewed your PR yet. I think we should document all the methods and events which are implemented in component by @rowanwins

**Comment by AlexanderYW** [comment]
Noted, i just wanted to make sure 😊

**Comment by vrajroham** [comment]
Cool! Great work buddy. 👍

**Comment by rowanwins** [comment]
Thanks so much for taking the time on this pull request @AlexanderYW - greatly appreciated! 

If you've got a bit of time and would like to contribute further I'd be happy to grant you access to be a contributor.

**Comment by AlexanderYW** [comment]
Hi, thanks for the appreciations guys!

@rowanwins, I dont mind being listed as a contributor since I'm planning on contributing more, but I dont want the access level as the contributor role has :) (at least for now)

**Pull request merged**
