### PR TITLE
Fixed uploadMultiple and parallelUpload for multiple files upload

### PR DESCRIPTION
**Pull request by atheleron**
I have fixed the issue with _POST REQUEST_ actually inside index.vue already was *uploadMultiple* function but **npm package** is outdated and **uploadMultiple** is missing inside npm but there was another issue with **parallelUploads** that defaults **2** files per one _POST REQUEST_ and inside index.vue was no override for that function so I have added that missing piece of code just make shure that u update npm package after this so other user's can have all updates :)

### CODE REVIEW

**Comment by vrajroham** [comment]
@atheleron Ohh gosh! My bad :see_no_evil: ! Don't know but I really forgot to add this parameter while fixing other issues. True saying **Make sure your one fix doesn't create other issue**. Learning from experience. @atheleron thanks for taking your time.

**Comment by vrajroham** [comment]
I'll resolve conflicts and merge it soon :timer_clock: .

**Comment by atheleron** [comment]
ohh gosh dont know why those bundle.js files are here anyway maybe I should just git index.vue

**Comment by vrajroham** [comment]
@atheleron that bundle files contains compiled code which you modified. Don't worry. 
Happy Coding. :+1:

**Pull request merged**
