### PR TITLE
Expose dropzone emit and createThumbnailFromUrl functionality.

### LINKED ISSUE #8: Assigning file container with files on the server
I couldn't find any documentation on assigning the drop zone container files.  Lets say you have a update form and your database pulls the image names form the server. Would be nice to see a example of assigning the file container the files that are already on the server.

### PR DESCRIPTION
**Pull request by holic-cl**
Add decrementFileCounter method to decrement the dropzone
 option.maxFiles value.

 This resolve #8 and allow to show files already stored on server.

### CODE REVIEW

**Comment by rowanwins** [comment]
Hi @holic-cl 

Thanks so much for taking the time to look into this. 

Did you think about creating a single method for manually adding the file to make the process a bit cleaner for people?

````
// In the parent component
this.$refs.myVueDropzone.manuallyAddFile(file, fileUrl, callback, crossorigin)

// In vue-dropzone
methods: {
   manuallyAddFile: function (file, fileUrl, callback, crossorigin) {
      this.dropzone.emit("addedfile", file);
     this.dropzone.emit("thumbnail", file,  fileUrl);
     this.dropzone.createThumbnailFromUrl(file, fileUrl, callback, crossOrigin);
     this.dropzone.emit("complete", mockFile);
   }
}
```
 I must admit I haven't thought about it much but the above approach seems like it might make life a bit easier for people?

Thanks,
Rowan

**Comment by holic-cl** [comment]
Hi

Ok, np, i will update the PR

**Comment by holic-cl** [comment]
Sorry for the inactivity, i already added the changes.

Greetings.

**Comment by rowanwins** [comment]
Hey @holic-cl , thanks for your code, I've adapted it a bit and we now have a new method called `manuallyAddFile` which I've released to npm as v2.2.6

**Pull request closed without merging**
