### PR TITLE
configurable optional duplicate check

### PR DESCRIPTION
**Pull request by rifaideen**
#129  Added configurable optional duplicate check and emit the **duplicate-file** event

### CODE REVIEW

**Comment by vrajroham** [comment]
:+1: 
Thanks for contribution! Whenever I'll get time I'll review and merge it! 

Happy coding :computer:

**Comment by vrajroham** [comment]
Hey @rifaideen it would be grate if you add docs about `prop` and `event` in `README.md`.

**Comment by rifaideen** [comment]
Ok, I will do and commit in same PR

**Comment by rifaideen** [comment]
@vrajroham can you resolve conflicts and merge the pull request?

**Comment by vrajroham** [comment]
@rifaideen No worry I'll do it!

**Comment by rifaideen** [comment]
@vrajroham ok.

**Pull request merged**
